// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.soniq.music

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object AudioScannerApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Generated class from Pigeon that represents data sent in messages. */
data class RawSongData (
  val id: Long? = null,
  val path: String? = null,
  val albumId: Long? = null,
  val dateAdded: Long? = null,
  val title: String? = null,
  val artist: String? = null,
  val album: String? = null,
  val albumArtist: String? = null,
  val genre: String? = null,
  val durationMs: Long? = null,
  val trackNumber: Long? = null,
  val discNumber: Long? = null,
  val year: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RawSongData {
      val id = pigeonVar_list[0] as Long?
      val path = pigeonVar_list[1] as String?
      val albumId = pigeonVar_list[2] as Long?
      val dateAdded = pigeonVar_list[3] as Long?
      val title = pigeonVar_list[4] as String?
      val artist = pigeonVar_list[5] as String?
      val album = pigeonVar_list[6] as String?
      val albumArtist = pigeonVar_list[7] as String?
      val genre = pigeonVar_list[8] as String?
      val durationMs = pigeonVar_list[9] as Long?
      val trackNumber = pigeonVar_list[10] as Long?
      val discNumber = pigeonVar_list[11] as Long?
      val year = pigeonVar_list[12] as Long?
      return RawSongData(id, path, albumId, dateAdded, title, artist, album, albumArtist, genre, durationMs, trackNumber, discNumber, year)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      path,
      albumId,
      dateAdded,
      title,
      artist,
      album,
      albumArtist,
      genre,
      durationMs,
      trackNumber,
      discNumber,
      year,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RawSongData
    return AudioScannerApiPigeonUtils.deepEquals(this.id, other.id) && AudioScannerApiPigeonUtils.deepEquals(this.path, other.path) && AudioScannerApiPigeonUtils.deepEquals(this.albumId, other.albumId) && AudioScannerApiPigeonUtils.deepEquals(this.dateAdded, other.dateAdded) && AudioScannerApiPigeonUtils.deepEquals(this.title, other.title) && AudioScannerApiPigeonUtils.deepEquals(this.artist, other.artist) && AudioScannerApiPigeonUtils.deepEquals(this.album, other.album) && AudioScannerApiPigeonUtils.deepEquals(this.albumArtist, other.albumArtist) && AudioScannerApiPigeonUtils.deepEquals(this.genre, other.genre) && AudioScannerApiPigeonUtils.deepEquals(this.durationMs, other.durationMs) && AudioScannerApiPigeonUtils.deepEquals(this.trackNumber, other.trackNumber) && AudioScannerApiPigeonUtils.deepEquals(this.discNumber, other.discNumber) && AudioScannerApiPigeonUtils.deepEquals(this.year, other.year)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + AudioScannerApiPigeonUtils.deepHash(this.id)
    result = 31 * result + AudioScannerApiPigeonUtils.deepHash(this.path)
    result = 31 * result + AudioScannerApiPigeonUtils.deepHash(this.albumId)
    result = 31 * result + AudioScannerApiPigeonUtils.deepHash(this.dateAdded)
    result = 31 * result + AudioScannerApiPigeonUtils.deepHash(this.title)
    result = 31 * result + AudioScannerApiPigeonUtils.deepHash(this.artist)
    result = 31 * result + AudioScannerApiPigeonUtils.deepHash(this.album)
    result = 31 * result + AudioScannerApiPigeonUtils.deepHash(this.albumArtist)
    result = 31 * result + AudioScannerApiPigeonUtils.deepHash(this.genre)
    result = 31 * result + AudioScannerApiPigeonUtils.deepHash(this.durationMs)
    result = 31 * result + AudioScannerApiPigeonUtils.deepHash(this.trackNumber)
    result = 31 * result + AudioScannerApiPigeonUtils.deepHash(this.discNumber)
    result = 31 * result + AudioScannerApiPigeonUtils.deepHash(this.year)
    return result
  }
  override fun toString(): String {
    return "RawSongData(id=$id, path=$path, albumId=$albumId, dateAdded=$dateAdded, title=$title, artist=$artist, album=$album, albumArtist=$albumArtist, genre=$genre, durationMs=$durationMs, trackNumber=$trackNumber, discNumber=$discNumber, year=$year)"
  }
}
private open class AudioScannerApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RawSongData.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is RawSongData -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface AudioScannerApi {
  fun querySongs(): List<RawSongData?>?
  fun querySongsSince(timestamp: Long): List<RawSongData?>?
  fun queryAlbumArt(albumId: Long, songId: Long): ByteArray?

  companion object {
    /** The codec used by AudioScannerApi. */
    val codec: MessageCodec<Any?> by lazy {
      AudioScannerApiPigeonCodec()
    }
    /** Sets up an instance of `AudioScannerApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: AudioScannerApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      val taskQueue = binaryMessenger.makeBackgroundTaskQueue()
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.soniq.AudioScannerApi.querySongs$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.querySongs())
            } catch (exception: Throwable) {
              AudioScannerApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.soniq.AudioScannerApi.querySongsSince$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val timestampArg = args[0] as Long
            val wrapped: List<Any?> = try {
              listOf(api.querySongsSince(timestampArg))
            } catch (exception: Throwable) {
              AudioScannerApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.soniq.AudioScannerApi.queryAlbumArt$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val albumIdArg = args[0] as Long
            val songIdArg = args[1] as Long
            val wrapped: List<Any?> = try {
              listOf(api.queryAlbumArt(albumIdArg, songIdArg))
            } catch (exception: Throwable) {
              AudioScannerApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
