name: soniq
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.17+17

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  drift: ^2.34.0
  drift_flutter: ^0.3.0
  sqlite3_flutter_libs: ^0.6.0
  path_provider: ^2.1.6
  path: ^1.9.1
  just_audio: ^0.10.6
  audio_service: ^0.18.19
  audio_session: ^0.2.4
  flutter_riverpod: ^2.6.1
  dynamic_color: ^1.8.1
  firebase_core: ^4.11.0
  firebase_crashlytics: ^5.2.4
  on_audio_query: ^2.9.0
  permission_handler: ^12.0.3
  crypto: ^3.0.7
  device_info_plus: ^11.5.0
  convert: ^3.1.2
  flutter_media_metadata_plus: any
  palette_generator: ^0.3.3+7
  meta: ^1.18.0
  http: ^1.6.0
  connectivity_plus: ^7.2.0
  shared_preferences: ^2.5.5
  sleek_circular_slider: ^2.1.0
  share_plus: ^12.0.2
  file_picker: ^8.1.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  pigeon: ^27.0.0
  drift_dev: ^2.34.0
  build_runner: ^2.15.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  # Folder declarations include all bundled files automatically
  assets:
    - assets/
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 24
  adaptive_icon_background: "#0A0A0A"
  adaptive_icon_foreground: "assets/icon/app_icon.png"